import { Poppins } from "next/font/google";
import "@/assets/styles/globals.css";
import ReduxProvider from "@/services/redux/redux-provider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>{children}</ReduxProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
